#ifndef _ARDUINO_H_m
#define _ARDUINO_H_m

#include <stdint.h>
#include <stdio.h>

typedef const char* String;
typedef unsigned char byte;

class usb_serial_class
{
public:
  void begin(int baudrate);
  bool available();
  char read();
  void print(char);
};

//usb_serial_class Serial;

uint32_t micros();
void digitalWrite(char *pinName, int value);
void analogWrite(char *pinName, int value);
bool digitalRead(char *pinName);

extern int currentTime;
extern bool no_prompt;

#define HIGH 1
#define LOW 0

#define CHANGE 1

#define OUTPUT 0x1
#define INPUT_PULLUP 0x2

void initInterrupts();
void X_encoderInterrupt();
void X_endStopInterrupt();
void attachInterrupt(char *pinName, void (*userFunc)(void), uint8_t mode);
void pinMode(char *pinName, uint8_t mode);

////////////////////////////////////
// Teensy++ 1.0 & 2.0
////////////////////////////////////
#define LED_BUILTIN "LED_BUILTIN"
#define CORE_NUM_TOTAL_PINS 46
#define CORE_NUM_DIGITAL 38
#define CORE_NUM_ANALOG 8
#define CORE_NUM_PWM 9
#define CORE_NUM_INTERRUPT 8
#define PIN_D0 "PIN_D0"
#define PIN_D1 "PIN_D1"
#define PIN_D2 "PIN_D2"
#define PIN_D3 "PIN_D3"
#define PIN_D4 "PIN_D4"
#define PIN_D5 "PIN_D5"
#define PIN_D6 "PIN_D6"
#define PIN_D7 "PIN_D7"
#define PIN_E0 "PIN_E0"
#define PIN_E1 "PIN_E1"
#define PIN_C0 "PIN_C0"
#define PIN_C1 "PIN_C1"
#define PIN_C2 "PIN_C2"
#define PIN_C3 "PIN_C3"
#define PIN_C4 "PIN_C4"
#define PIN_C5 "PIN_C5"
#define PIN_C6 "PIN_C6"
#define PIN_C7 "PIN_C7"
#define PIN_E6 "PIN_E6"
#define PIN_E7 "PIN_E7"
#define PIN_SS "PIN_SS"
#define PIN_SCLK 21
#define PIN_MOSI 22
#define PIN_MISO 23
#define PIN_B0 "PIN_B0"
#define PIN_B1 "PIN_B1"
#define PIN_B2 "PIN_B2"
#define PIN_B3 "PIN_B3"
#define PIN_B4 "PIN_B4"
#define PIN_B5 "PIN_B5"
#define PIN_B6 "PIN_B6"
#define PIN_B7 "PIN_B7"
#define PIN_A0 "PIN_A0"
#define PIN_A1 "PIN_A1"
#define PIN_A2 "PIN_A2"
#define PIN_A3 "PIN_A3"
#define PIN_A4 "PIN_A4"
#define PIN_A5 "PIN_A5"
#define PIN_A6 "PIN_A6"
#define PIN_A7 "PIN_A7"
#define PIN_E4 "PIN_E4"
#define PIN_E5 "PIN_E5"
#define PIN_F0 "PIN_F0"
#define PIN_F1 "PIN_F1"
#define PIN_F2 "PIN_F2"
#define PIN_F3 "PIN_F3"
#define PIN_F4 "PIN_F4"
#define PIN_F5 "PIN_F5"
#define PIN_F6 "PIN_F6"
#define PIN_F7 "PIN_F7"
#define CORE_PIN0_BIT 0
#define CORE_PIN1_BIT 1
#define CORE_PIN2_BIT 2
#define CORE_PIN3_BIT 3
#define CORE_PIN4_BIT 4
#define CORE_PIN5_BIT 5
#define CORE_PIN6_BIT 6
#define CORE_PIN7_BIT 7
#define CORE_PIN8_BIT 0
#define CORE_PIN9_BIT 1
#define CORE_PIN10_BIT 0
#define CORE_PIN11_BIT 1
#define CORE_PIN12_BIT 2
#define CORE_PIN13_BIT 3
#define CORE_PIN14_BIT 4
#define CORE_PIN15_BIT 5
#define CORE_PIN16_BIT 6
#define CORE_PIN17_BIT 7
#define CORE_PIN18_BIT 6
#define CORE_PIN19_BIT 7
#define CORE_PIN20_BIT 0
#define CORE_PIN21_BIT 1
#define CORE_PIN22_BIT 2
#define CORE_PIN23_BIT 3
#define CORE_PIN24_BIT 4
#define CORE_PIN25_BIT 5
#define CORE_PIN26_BIT 6
#define CORE_PIN27_BIT 7
#define CORE_PIN28_BIT 0
#define CORE_PIN29_BIT 1
#define CORE_PIN30_BIT 2
#define CORE_PIN31_BIT 3
#define CORE_PIN32_BIT 4
#define CORE_PIN33_BIT 5
#define CORE_PIN34_BIT 6
#define CORE_PIN35_BIT 7
#define CORE_PIN36_BIT 4
#define CORE_PIN37_BIT 5
#define CORE_PIN38_BIT 0
#define CORE_PIN39_BIT 1
#define CORE_PIN40_BIT 2
#define CORE_PIN41_BIT 3
#define CORE_PIN42_BIT 4
#define CORE_PIN43_BIT 5
#define CORE_PIN44_BIT 6
#define CORE_PIN45_BIT 7
#define CORE_PIN0_BITMASK _BV(CORE_PIN0_BIT)
#define CORE_PIN1_BITMASK _BV(CORE_PIN1_BIT)
#define CORE_PIN2_BITMASK _BV(CORE_PIN2_BIT)
#define CORE_PIN3_BITMASK _BV(CORE_PIN3_BIT)
#define CORE_PIN4_BITMASK _BV(CORE_PIN4_BIT)
#define CORE_PIN5_BITMASK _BV(CORE_PIN5_BIT)
#define CORE_PIN6_BITMASK _BV(CORE_PIN6_BIT)
#define CORE_PIN7_BITMASK _BV(CORE_PIN7_BIT)
#define CORE_PIN8_BITMASK _BV(CORE_PIN8_BIT)
#define CORE_PIN9_BITMASK _BV(CORE_PIN9_BIT)
#define CORE_PIN10_BITMASK _BV(CORE_PIN10_BIT)
#define CORE_PIN11_BITMASK _BV(CORE_PIN11_BIT)
#define CORE_PIN12_BITMASK _BV(CORE_PIN12_BIT)
#define CORE_PIN13_BITMASK _BV(CORE_PIN13_BIT)
#define CORE_PIN14_BITMASK _BV(CORE_PIN14_BIT)
#define CORE_PIN15_BITMASK _BV(CORE_PIN15_BIT)
#define CORE_PIN16_BITMASK _BV(CORE_PIN16_BIT)
#define CORE_PIN17_BITMASK _BV(CORE_PIN17_BIT)
#define CORE_PIN18_BITMASK _BV(CORE_PIN18_BIT)
#define CORE_PIN19_BITMASK _BV(CORE_PIN19_BIT)
#define CORE_PIN20_BITMASK _BV(CORE_PIN20_BIT)
#define CORE_PIN21_BITMASK _BV(CORE_PIN21_BIT)
#define CORE_PIN22_BITMASK _BV(CORE_PIN22_BIT)
#define CORE_PIN23_BITMASK _BV(CORE_PIN23_BIT)
#define CORE_PIN24_BITMASK _BV(CORE_PIN24_BIT)
#define CORE_PIN25_BITMASK _BV(CORE_PIN25_BIT)
#define CORE_PIN26_BITMASK _BV(CORE_PIN26_BIT)
#define CORE_PIN27_BITMASK _BV(CORE_PIN27_BIT)
#define CORE_PIN28_BITMASK _BV(CORE_PIN28_BIT)
#define CORE_PIN29_BITMASK _BV(CORE_PIN29_BIT)
#define CORE_PIN30_BITMASK _BV(CORE_PIN30_BIT)
#define CORE_PIN31_BITMASK _BV(CORE_PIN31_BIT)
#define CORE_PIN32_BITMASK _BV(CORE_PIN32_BIT)
#define CORE_PIN33_BITMASK _BV(CORE_PIN33_BIT)
#define CORE_PIN34_BITMASK _BV(CORE_PIN34_BIT)
#define CORE_PIN35_BITMASK _BV(CORE_PIN35_BIT)
#define CORE_PIN36_BITMASK _BV(CORE_PIN36_BIT)
#define CORE_PIN37_BITMASK _BV(CORE_PIN37_BIT)
#define CORE_PIN38_BITMASK _BV(CORE_PIN38_BIT)
#define CORE_PIN39_BITMASK _BV(CORE_PIN39_BIT)
#define CORE_PIN40_BITMASK _BV(CORE_PIN40_BIT)
#define CORE_PIN41_BITMASK _BV(CORE_PIN41_BIT)
#define CORE_PIN42_BITMASK _BV(CORE_PIN42_BIT)
#define CORE_PIN43_BITMASK _BV(CORE_PIN43_BIT)
#define CORE_PIN44_BITMASK _BV(CORE_PIN44_BIT)
#define CORE_PIN45_BITMASK _BV(CORE_PIN45_BIT)
#define CORE_PIN0_PORTREG PORTD
#define CORE_PIN1_PORTREG PORTD
#define CORE_PIN2_PORTREG PORTD
#define CORE_PIN3_PORTREG PORTD
#define CORE_PIN4_PORTREG PORTD
#define CORE_PIN5_PORTREG PORTD
#define CORE_PIN6_PORTREG PORTD
#define CORE_PIN7_PORTREG PORTD
#define CORE_PIN8_PORTREG PORTE
#define CORE_PIN9_PORTREG PORTE
#define CORE_PIN10_PORTREG PORTC
#define CORE_PIN11_PORTREG PORTC
#define CORE_PIN12_PORTREG PORTC
#define CORE_PIN13_PORTREG PORTC
#define CORE_PIN14_PORTREG PORTC
#define CORE_PIN15_PORTREG PORTC
#define CORE_PIN16_PORTREG PORTC
#define CORE_PIN17_PORTREG PORTC
#define CORE_PIN18_PORTREG PORTE
#define CORE_PIN19_PORTREG PORTE
#define CORE_PIN20_PORTREG PORTB
#define CORE_PIN21_PORTREG PORTB
#define CORE_PIN22_PORTREG PORTB
#define CORE_PIN23_PORTREG PORTB
#define CORE_PIN24_PORTREG PORTB
#define CORE_PIN25_PORTREG PORTB
#define CORE_PIN26_PORTREG PORTB
#define CORE_PIN27_PORTREG PORTB
#define CORE_PIN28_PORTREG PORTA
#define CORE_PIN29_PORTREG PORTA
#define CORE_PIN30_PORTREG PORTA
#define CORE_PIN31_PORTREG PORTA
#define CORE_PIN32_PORTREG PORTA
#define CORE_PIN33_PORTREG PORTA
#define CORE_PIN34_PORTREG PORTA
#define CORE_PIN35_PORTREG PORTA
#define CORE_PIN36_PORTREG PORTE
#define CORE_PIN37_PORTREG PORTE
#define CORE_PIN38_PORTREG PORTF
#define CORE_PIN39_PORTREG PORTF
#define CORE_PIN40_PORTREG PORTF
#define CORE_PIN41_PORTREG PORTF
#define CORE_PIN42_PORTREG PORTF
#define CORE_PIN43_PORTREG PORTF
#define CORE_PIN44_PORTREG PORTF
#define CORE_PIN45_PORTREG PORTF
#define CORE_PIN0_DDRREG DDRD
#define CORE_PIN1_DDRREG DDRD
#define CORE_PIN2_DDRREG DDRD
#define CORE_PIN3_DDRREG DDRD
#define CORE_PIN4_DDRREG DDRD
#define CORE_PIN5_DDRREG DDRD
#define CORE_PIN6_DDRREG DDRD
#define CORE_PIN7_DDRREG DDRD
#define CORE_PIN8_DDRREG DDRE
#define CORE_PIN9_DDRREG DDRE
#define CORE_PIN10_DDRREG DDRC
#define CORE_PIN11_DDRREG DDRC
#define CORE_PIN12_DDRREG DDRC
#define CORE_PIN13_DDRREG DDRC
#define CORE_PIN14_DDRREG DDRC
#define CORE_PIN15_DDRREG DDRC
#define CORE_PIN16_DDRREG DDRC
#define CORE_PIN17_DDRREG DDRC
#define CORE_PIN18_DDRREG DDRE
#define CORE_PIN19_DDRREG DDRE
#define CORE_PIN20_DDRREG DDRB
#define CORE_PIN21_DDRREG DDRB
#define CORE_PIN22_DDRREG DDRB
#define CORE_PIN23_DDRREG DDRB
#define CORE_PIN24_DDRREG DDRB
#define CORE_PIN25_DDRREG DDRB
#define CORE_PIN26_DDRREG DDRB
#define CORE_PIN27_DDRREG DDRB
#define CORE_PIN28_DDRREG DDRA
#define CORE_PIN29_DDRREG DDRA
#define CORE_PIN30_DDRREG DDRA
#define CORE_PIN31_DDRREG DDRA
#define CORE_PIN32_DDRREG DDRA
#define CORE_PIN33_DDRREG DDRA
#define CORE_PIN34_DDRREG DDRA
#define CORE_PIN35_DDRREG DDRA
#define CORE_PIN36_DDRREG DDRE
#define CORE_PIN37_DDRREG DDRE
#define CORE_PIN38_DDRREG DDRF
#define CORE_PIN39_DDRREG DDRF
#define CORE_PIN40_DDRREG DDRF
#define CORE_PIN41_DDRREG DDRF
#define CORE_PIN42_DDRREG DDRF
#define CORE_PIN43_DDRREG DDRF
#define CORE_PIN44_DDRREG DDRF
#define CORE_PIN45_DDRREG DDRF
#define CORE_PIN0_PINREG PIND
#define CORE_PIN1_PINREG PIND
#define CORE_PIN2_PINREG PIND
#define CORE_PIN3_PINREG PIND
#define CORE_PIN4_PINREG PIND
#define CORE_PIN5_PINREG PIND
#define CORE_PIN6_PINREG PIND
#define CORE_PIN7_PINREG PIND
#define CORE_PIN8_PINREG PINE
#define CORE_PIN9_PINREG PINE
#define CORE_PIN10_PINREG PINC
#define CORE_PIN11_PINREG PINC
#define CORE_PIN12_PINREG PINC
#define CORE_PIN13_PINREG PINC
#define CORE_PIN14_PINREG PINC
#define CORE_PIN15_PINREG PINC
#define CORE_PIN16_PINREG PINC
#define CORE_PIN17_PINREG PINC
#define CORE_PIN18_PINREG PINE
#define CORE_PIN19_PINREG PINE
#define CORE_PIN20_PINREG PINB
#define CORE_PIN21_PINREG PINB
#define CORE_PIN22_PINREG PINB
#define CORE_PIN23_PINREG PINB
#define CORE_PIN24_PINREG PINB
#define CORE_PIN25_PINREG PINB
#define CORE_PIN26_PINREG PINB
#define CORE_PIN27_PINREG PINB
#define CORE_PIN28_PINREG PINA
#define CORE_PIN29_PINREG PINA
#define CORE_PIN30_PINREG PINA
#define CORE_PIN31_PINREG PINA
#define CORE_PIN32_PINREG PINA
#define CORE_PIN33_PINREG PINA
#define CORE_PIN34_PINREG PINA
#define CORE_PIN35_PINREG PINA
#define CORE_PIN36_PINREG PINE
#define CORE_PIN37_PINREG PINE
#define CORE_PIN38_PINREG PINF
#define CORE_PIN39_PINREG PINF
#define CORE_PIN40_PINREG PINF
#define CORE_PIN41_PINREG PINF
#define CORE_PIN42_PINREG PINF
#define CORE_PIN43_PINREG PINF
#define CORE_PIN44_PINREG PINF
#define CORE_PIN45_PINREG PINF
#define CORE_ADC0_PIN PIN_F0
#define CORE_ADC1_PIN PIN_F1
#define CORE_ADC2_PIN PIN_F2
#define CORE_ADC3_PIN PIN_F3
#define CORE_ADC4_PIN PIN_F4
#define CORE_ADC5_PIN PIN_F5
#define CORE_ADC6_PIN PIN_F6
#define CORE_ADC7_PIN PIN_F7
#define CORE_RXD1_PIN PIN_D2
#define CORE_TXD1_PIN PIN_D3
#define CORE_XCK1_PIN PIN_D5
#define CORE_SDA0_PIN PIN_D1
#define CORE_SCL0_PIN PIN_D0
#define CORE_INT0_PIN PIN_D0
#define CORE_INT1_PIN PIN_D1
#define CORE_INT2_PIN PIN_D2
#define CORE_INT3_PIN PIN_D3
#define CORE_INT4_PIN PIN_E4
#define CORE_INT5_PIN PIN_E5
#define CORE_INT6_PIN PIN_E6
#define CORE_INT7_PIN PIN_E7
#define CORE_SS0_PIN PIN_B0
#define CORE_MOSI0_PIN PIN_B2
#define CORE_MISO0_PIN PIN_B3
#define CORE_SCLK0_PIN PIN_B1
#define CORE_T0_PIN PIN_D7
#define CORE_T1_PIN PIN_D6
#define CORE_ICP1_PIN PIN_D4
#define CORE_ICP3_PIN PIN_C7
#define CORE_OC0A_PIN PIN_B7
#define CORE_OC0B_PIN PIN_D0
#define CORE_OC1A_PIN PIN_B5
#define CORE_OC1B_PIN PIN_B6
#define CORE_OC1C_PIN PIN_B7
#define CORE_OC2A_PIN PIN_B4
#define CORE_OC2B_PIN PIN_D1
#define CORE_OC3A_PIN PIN_C6
#define CORE_OC3B_PIN PIN_C5
#define CORE_OC3C_PIN PIN_C4
#define CORE_PCINT0_PIN PIN_B0
#define CORE_PCINT1_PIN PIN_B1
#define CORE_PCINT2_PIN PIN_B2
#define CORE_PCINT3_PIN PIN_B3
#define CORE_PCINT4_PIN PIN_B4
#define CORE_PCINT5_PIN PIN_B5
#define CORE_PCINT6_PIN PIN_B6
#define CORE_PCINT7_PIN PIN_B7
#define CORE_LED0_PIN PIN_D6
#define CORE_PWM0_PIN CORE_OC0B_PIN // D0, 0
#define CORE_PWM1_PIN CORE_OC2B_PIN // D1, 1
#define CORE_PWM2_PIN CORE_OC3C_PIN // C4, 14
#define CORE_PWM3_PIN CORE_OC3B_PIN // C5, 15
#define CORE_PWM4_PIN CORE_OC3A_PIN // C6, 16
#define CORE_PWM5_PIN CORE_OC2A_PIN // B4, 24
#define CORE_PWM6_PIN CORE_OC1A_PIN // B5, 25
#define CORE_PWM7_PIN CORE_OC1B_PIN // B6, 26
#define CORE_PWM8_PIN CORE_OC1C_PIN // B7, 27
#define CORE_ANALOG0_PIN PIN_F0
#define CORE_ANALOG1_PIN PIN_F1
#define CORE_ANALOG2_PIN PIN_F2
#define CORE_ANALOG3_PIN PIN_F3
#define CORE_ANALOG4_PIN PIN_F4
#define CORE_ANALOG5_PIN PIN_F5
#define CORE_ANALOG6_PIN PIN_F6
#define CORE_ANALOG7_PIN PIN_F7

#endif